spring:
  cloud:
    gateway:
      routes:
        - id: ai
          uri: lb://ai
          predicates:
            - Path=/api/ai/**
          filters:
            - RewritePath=/api/ai/?(?<segment>.*),/$\{segment}

        - id: user
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/?(?<segment>.*),/$\{segment}

        - id: dishes
          uri: lb://dishes
          predicates:
            - Path=/api/dishes/**
          filters:
            - RewritePath=/api/dishes/?(?<segment>.*),/$\{segment}

        - id: testb-route
          uri: lb://testb
          predicates:
            - Path=/api/testb/**
          filters:
            - RewritePath=/api/testb/?(?<segment>.*),/$\{segment}

        - id: testa-route
          uri: lb://testa
          predicates:
            - Path=/api/testa/**
          filters:
            - RewritePath=/api/testa/?(?<segment>.*),/$\{segment}